name: Github Workflow

on:
  push:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo Github Actions
        run: echo "Hello world to GITHUB ACTIONS"
