name: Github Workflow

on:
  push:
    branches:
      - main

env:
  NAME: "MUHAMMED JIMOH"
  PROFESSION: "DATA ENGINEER"
  PASSION: "DATA ENTHUSIAST"

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t demo .

  post-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Post-build Steps
        run: echo "POST-BUILD STEPS AFTER EXCUTION OF THE ABOVE STEPS"
