name: Github Workflow

on:
  push:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo Github Actions
        run: ls -al

  post-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Post-build Steps
        run: echo "POST-BUILD STEPS AFTER EXCUTION OF THE ABOVE STEPS"
